### ISSUE TITLE
Are you open to convenient type class interface?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskellari/strict#32]
A few weeks ago I wrote up [an article](http://h2.jaguarpaw.co.uk/posts/nested-strict-data/) explaining how to make a convenient type class interface to strict data types. The interface avoids the user having to interact directly with a "parallel universe" of strict data types. Interacting with two new functions and one new pattern is sufficient. Subsequently I added a section about how this can be done at zero additional run time cost (I believe -- I have not benchmarked or inspected core). I have put up [a simple implementation of the idea](https://github.com/tomjaguarpaw/ad/blob/190b17837c958eb43c90deffbf151407ebad0268/stricter/lib/Strict.hs).

Would you be open to receiving this as a contribution of a new module to the `strict` library? The alternative is that make a separate package but I think it's better not to fragment the ecosystem.

**Comment by phadej** [comment]
Does your proposal add anything else then essentially turning the `Strict` class we have

```haskell
class Strict strict lazy where
  toLazy :: strict -> lazy
  toStrict :: lazy -> strict
```

into

```haskell
class Strictly lazy where
   type Strict lazy :: Type
   toLazy :: Strict lazy -> lazy
   toStrict :: lazy -> Strict lazy
```

?

**Comment by tomjaguarpaw** [comment]
Denotationally, it is very close to what you say. N.B. in my implementation `Strict` is a *data* family, to avoid the implementation details leaking. I find  the data family more ergonomic than the MPTC. With a data family there is no need to use (or remember) the names of the strict types.

Operationally, I hope that my implementation is rather more efficient. I've gone to some trouble to minimise allocation, as explained in the ["Performance impact" section of my article](http://h2.jaguarpaw.co.uk/posts/nested-strict-data/#performance-impact).

**Comment by phadej** [comment]
But then (with `data family`) we have an annoying wrapper around `Strict Text` (or Lazy if done other way around).

I'm not convinced. I usually prefer FunDeps over TFs.

---

Relatedly:

newtype Strict (Maybe a) = StrictMaybe (Data.Strict.Maybe a)

and

unstrict = unsafeCoerce

is plain wrong `Maybe` and `Data.Strict.Maybe` don't have the same representation.
